#!/usr/bin/env python3
"""
XOYO DOCX Generator — Word document creation microservice
Port: 8041
"""
from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import os, time

app = FastAPI()

class ParagraphData(BaseModel):
    text: str
    style: str = "Normal"       # Normal, Heading1, Heading2, Heading3
    bold: bool = False
    italic: bool = False
    alignment: str = "left"

class DocumentRequest(BaseModel):
    title: str
    author: str = "XOYO Omega"
    paragraphs: List[ParagraphData]
    output_filename: str = ""
    output_dir: str = os.path.expanduser("~/xoyo/output/documents")

@app.post("/generate")
async def generate_docx(req: DocumentRequest):
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    os.makedirs(req.output_dir, exist_ok=True)
    filename = req.output_filename or f"xoyo_doc_{int(time.time())}.docx"
    output_path = os.path.join(req.output_dir, filename)

    doc = Document()
    title_para = doc.add_heading(req.title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub.add_run(f"Generated by {req.author} · {time.strftime('%Y-%m-%d')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(128, 128, 128)

    style_map = {"Normal": 0, "Heading1": 1, "Heading2": 2, "Heading3": 3}
    align_map = {
        "center": WD_ALIGN_PARAGRAPH.CENTER,
        "right": WD_ALIGN_PARAGRAPH.RIGHT,
        "left": WD_ALIGN_PARAGRAPH.LEFT,
    }

    for item in req.paragraphs:
        level = style_map.get(item.style, 0)
        if level > 0:
            para = doc.add_heading(item.text, level=level)
        else:
            para = doc.add_paragraph()
            run = para.add_run(item.text)
            run.bold = item.bold
            run.italic = item.italic
        para.alignment = align_map.get(item.alignment, WD_ALIGN_PARAGRAPH.LEFT)

    doc.save(output_path)
    return {"status": "ok", "path": output_path, "paragraphs": len(req.paragraphs)}

@app.get("/health")
def health():
    return {"status": "ok", "service": "docx_generator", "port": 8041}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8041)
