#!/usr/bin/env python3
"""
XOYO PPT Generator — PowerPoint creation microservice
Port: 8040
"""
from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Optional
import os, time

app = FastAPI()

class SlideContent(BaseModel):
    title: str
    bullet_points: List[str] = []
    notes: Optional[str] = ""

class PresentationRequest(BaseModel):
    topic: str
    slides: List[SlideContent]
    output_filename: str = ""
    output_dir: str = os.path.expanduser("~/xoyo/output/presentations")

@app.post("/generate")
async def generate_ppt(req: PresentationRequest):
    from pptx import Presentation
    from pptx.util import Pt

    os.makedirs(req.output_dir, exist_ok=True)
    filename = req.output_filename or f"xoyo_ppt_{int(time.time())}.pptx"
    output_path = os.path.join(req.output_dir, filename)

    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = req.topic
    slide.placeholders[1].text = f"Generated by XOYO Omega — {time.strftime('%Y-%m-%d')}"

    # Content slides
    for sd in req.slides:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = sd.title
        tf = slide.placeholders[1].text_frame
        for i, bullet in enumerate(sd.bullet_points):
            if i == 0:
                tf.text = bullet
            else:
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 1
        if sd.notes:
            slide.notes_slide.notes_text_frame.text = sd.notes

    prs.save(output_path)
    return {"status": "ok", "path": output_path, "slides": len(req.slides) + 1}

@app.get("/health")
def health():
    return {"status": "ok", "service": "ppt_generator", "port": 8040}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8040)
